version: '3'

services:
  db:
    image: postgres:9.5
    container_name: postgres
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  odoo_master:
    image: odoo:12.0
    container_name: odoo12
    depends_on:
      - db
    ports:
      - "8012:8069"
    command: -- --dev=reload
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt
      - ./etc:/etc/odoo
    restart: always 

volumes:
    odoo-web-data:
    odoo-db-data:





